spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://kesavan.db.elephantsql.com:5432/qtvreryn?createDatabaseIfNotExist=true&useSSL=false
    username: qtvreryn
    password: TQoDf49Kt0wDOwg-RzhzmERkg7tOKFUe
    platform: postgres
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database: postgresql
server:
  error:
    include-stacktrace: never